prompt MISSING
SELECT LOCAL.THREAD#, LOCAL.SEQUENCE# FROM 
 (SELECT THREAD#, SEQUENCE# FROM V$ARCHIVED_LOG WHERE DEST_ID=1) 
 LOCAL WHERE 
 LOCAL.SEQUENCE# NOT IN 
 (SELECT SEQUENCE# FROM V$ARCHIVED_LOG WHERE DEST_ID=2 AND 
 THREAD# = LOCAL.THREAD#);


prompt GENERAL
SELECT PROTECTION_MODE, PROTECTION_LEVEL, 
 DATABASE_ROLE ROLE, SWITCHOVER_STATUS 
FROM V$DATABASE;


prompt SOURCE MAX ARCHIVED ARL
SELECT MAX(SEQUENCE#), THREAD# FROM V$ARCHIVED_LOG
WHERE RESETLOGS_CHANGE# = (SELECT MAX(RESETLOGS_CHANGE#) FROM V$ARCHIVED_LOG)
GROUP BY THREAD#;

col destination format a10
SELECT DESTINATION, STATUS, ARCHIVED_THREAD#, ARCHIVED_SEQ#
FROM V$ARCHIVE_DEST_STATUS
WHERE STATUS <> 'DEFERRED' AND STATUS <> 'INACTIVE';


prompt =======standby redo
SELECT GROUP#, BYTES FROM V$STANDBY_LOG;

prompt =======what was applied
select * from (
SELECT SEQUENCE#,APPLIED FROM V$ARCHIVED_LOG ORDER BY SEQUENCE# desc)
where rownum <10;

prompt ===> STATUS
SELECT PROCESS, STATUS, THREAD#, SEQUENCE#, BLOCK#, BLOCKS FROM V$MANAGED_STANDBY;

prompt RECEIVED
SELECT THREAD#, SEQUENCE#, FIRST_CHANGE#, NEXT_CHANGE# FROM V$ARCHIVED_LOG;

prompy on standby
SELECT NAME, VALUE, DATUM_TIME FROM V$DATAGUARD_STATS;
